### ISSUE TITLE
Add ability to run upstream testing github actions workflow manually

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/cookiecutter-nautobot-app#103]
### Environment

* cookiecutter-nautobot-app version:  2.2.1? Why is a version required for a feature request?

### Proposed Functionality

We need to add `workflow_dispatch` to the `on:` key of `nautobot-app/{{ cookiecutter.project_slug }}/.github/workflows/upstream_testing.yml` so that we can manually invoke this testing when preparing a new release of Nautobot core.

@glennmatthews thoughts on adding a `branch` argument to this workflow so we can specify which branch/tag to test against? We could have core's release workflow call this workflow and specify the release tag so before releasing a new minor version of Nautobot we would release a release candidate to initiate the upstream testing.

### Use Case

We'd like to manually invoke upstream testing before releasing a new version of Nautobot core to verify the apps won't be broken by any changes introduced in the new version.

**Comment by glennmatthews** [comment]
Re `branch` we currently have the scheduled workflow testing against both `ltm-1.6` and `develop` right? I would have naively thought it was already an option based on that. Agreed it would be useful!

**Comment by gsnider2195** [comment]
Those versions are hard coded [here](https://github.com/nautobot/nautobot/blob/322d1361ed9e4e50d80e9b8d1adaa5dd2b93fff2/.github/workflows/plugin_upstream_testing_base.yml#L23C47-L23C49)

**Comment by gsnider2195** [comment]
Fixed in v2.4.0
