### ISSUE TITLE
Broken link on CookieCutter docs for Nautobot-App-SSOT

### ISSUE THREAD

**Issue by collin-wicker** [nautobot/cookiecutter-nautobot-app#109]
### Environment

- https://docs.nautobot.com/projects/cookiecutter-nautobot-app/en/latest/#templates

### Observed Behaviour

- When clicking on nautobot-app-ssot link for cookiecutter docs for that app the link goes to a bad page:
https://docs.nautobot.com/projects/cookiecutter-nautobot-app/en/latest/nautobot-app-ssot

### Expected Behaviour

- Expected to be taken to a page explaining cookiecutter usage for nautobot-app-ssot.

### Steps to Reproduce

1. Navigate to https://docs.nautobot.com/projects/cookiecutter-nautobot-app/en/latest/#templates
2. Under Templates section click on the nautobot-app-ssot link
3. Link goes to https://docs.nautobot.com/projects/cookiecutter-nautobot-app/en/latest/nautobot-app-ssot which produces a 404 error.

**Comment by Renrut5** [comment]
404 error also on `nautobot-app` and `nautobot-app-chatops`.

**Comment by Renrut5** [comment]
The 404 error only comes up when clicking the links from generated docs. Clicking the links works as expected from GitHub README view.

@gsnider2195 , this may not be an actual issue to be fixed, and closing may be recommended.
