### ISSUE TITLE
Add support for Python 3.12 to the Nautobot App cookie

### ISSUE THREAD

**Issue by cmsirbu** [nautobot/cookiecutter-nautobot-app#129]
Nautobot 2.3 supports Python 3.12, so should we across our templates and apps.

**Comment by gsnider2195** [comment]
A separate issue will be opened for deploying this out to all of the apps. This issue will just be updating the cookie itself.

**Comment by bryanculver** [comment]
Let's:
- Test this in a couple repo with some "hypothetical" drift management PRs
- Add an invoke command that run through the CI-like step to be able to reproduce any possible CI problems locally
