### ISSUE TITLE
Remove bandit completely

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/cookiecutter-nautobot-app#143]
Ruff bandit is a drop-in replacement for bandit. We need to remove bandit in the cookie now that ruff bandit rules are enabled.

**Comment by gsnider2195** [comment]
Put directly into the cookie (skip app-dev-example) since we've already done this work on multiple real apps

**Comment by cmsirbu** [comment]
And disable pylint rules in the ruff section.
