### ISSUE TITLE
Change Default Behavior to Create Model Example

### ISSUE THREAD

**Issue by bryanculver** [nautobot/cookiecutter-nautobot-app#190]
Provide the user the option to override the initial model name created but the current default behavior skips generating these files which then gets lost when managing drift as well as forces the user to manually create these files, often far adrift from standard.

https://github.com/nautobot/cookiecutter-nautobot-app/blob/566d869ef93f461214aedb55c0f4cddada41e415/nautobot-app/hooks/post_gen_project.py#L27-L48

To resolve the "missed when drift managed" issue in other Apps, update the `.cookiecutter.json` file in the repo to have `model_class_name` be the name of one of the models in the App (ex: `"model_class_name": "GoldenConfig"` for Golden Config). The value should be left as `"None"` for any App that does not contain any models.

**Comment by gsnider2195** [comment]
It looks like cookiecutter doesn't provide us with any advanced prompt manipulation so I propose we set the default `model_class_name` to `{{ cookiecutter.camel_name }}ExampleModel }}` and modify the [prompt](https://cookiecutter.readthedocs.io/en/stable/advanced/human_readable_prompts.html) to let the user know to set it to `None` for no model:

```json
{
    "codeowner_github_usernames": "",
    "full_name": "Network to Code, LLC",
    "email": "info@networktocode.com",
    "github_org": "nautobot",
    "app_name": "my_app",
    "verbose_name": "{{ cookiecutter.app_name.title().replace('_', ' ') }}",
    "app_slug": "{{ cookiecutter.app_name.lower().replace(' ', '-').replace('_', '-') }}",
    "project_slug": "nautobot-app-{{ cookiecutter.app_slug }}",
    "repo_url": "https://github.com/{{ cookiecutter.github_org }}/{{ cookiecutter.project_slug }}",
    "base_url": "{{ cookiecutter.app_slug }}",
    "min_nautobot_version": "2.0.0",
    "max_nautobot_version": "2.9999",
    "camel_name": "{{ cookiecutter.app_slug.title().replace(' ', '').replace('-', '') }}",
    "project_short_description": "{{ cookiecutter.verbose_name }}",
    "model_class_name": "{{ cookiecutter.camel_name }}ExampleModel",
    "open_source_license": [
        "Apache-2.0",
        "Not open source"
    ],
    "docs_base_url": "https://docs.nautobot.com",
    "docs_app_url": "{{ cookiecutter.docs_base_url }}/projects/{{ cookiecutter.app_slug }}/en/latest",
    "__prompts__": {
        "model_class_name": "Select the name of your first database model. Set to 'None' if this app will have no models."
    }
}
```

**Comment by smk4664** [comment]
- [ ] "bgp-models" 
  - nautobot/nautobot-app-bgp-models#223
  - Contact Marek to review
- [ ] "capacity-metrics"
  - nautobot/nautobot-app-capacity-metrics#101
  - Inform Nikos of changes
- [x] "chatops"
  - nautobot/nautobot-app-chatops#337
  - Contact Stephen Kiely :)
- [x] "circuit-maintenance"
  - nautobot/nautobot-app-circuit-maintenance#326
  - Contact Stephen Corry
- [x] "data-validation-engine"
  - nautobot/nautobot-app-data-validation-engine#182
  - Contact Steven Weiblinger
- [x] "dev-example"
  - nautobot/nautobot-app-dev-example#52
- [x] "device-lifecycle-mgmt"
  - nautobot/nautobot-app-device-lifecycle-mgmt#381
  - Contact Przemek and Brad Haas
- [x] "device-onboarding"
  - nautobot/nautobot-app-device-onboarding#253
  - Contact Stephen Corry
- [x] "firewall-models"
  - nautobot/nautobot-app-firewall-models#278
  - Apps Team to review and merge
- [x] "floor-plan"
  - nautobot/nautobot-app-floor-plan#129
  - Contact Glenn
- [ ] "golden-config"
  - nautobot/nautobot-app-golden-config#818
  - Contact Ken
- [x] "netbox-importer"
  - nautobot/nautobot-app-netbox-importer#189
  - Apps team to review and merge
- [ ] "nornir-app"
  - nautobot/nautobot-app-nornir#181
  - Contact ??
- [x] "secrets-providers"
  - nautobot/nautobot-app-secrets-providers#154
  - Contact core team
- [x] "ssot"
  - nautobot/nautobot-app-ssot#567
  - Contact Justin Drew
- [x] "welcome-wizard"
  - nautobot/nautobot-app-welcome-wizard#117
  - Contact Stephen Kiely :)
