### ISSUE TITLE
Exit Exceptions Stopping `invoke tests` Execution

### ISSUE THREAD

**Issue by DistantVoyager** [nautobot/cookiecutter-nautobot-app#195]
### Environment

* Python version:  3.11
* cookiecutter-nautobot-app template version:  2.4.0

### Observed Behavior
`invoke tests` seems to be exiting immediately after the `ruff` test, even though the `ruff` test is passing.

```
(nautobot-data-validation-engine-py3.10) steven:~/nautobot-app-data-validation-engine$ invoke tests
Starting Docker Containers...
Starting Nautobot in detached mode...
Running docker compose command "up --detach"
 Container nautobot-data-validation-engine-redis-1  Running
 Container nautobot-data-validation-engine-docs-1  Running
 Container nautobot-data-validation-engine-db-1  Running
 Container nautobot-data-validation-engine-nautobot-1  Running
 Container nautobot-data-validation-engine-beat-1  Running
 Container nautobot-data-validation-engine-worker-1  Running
 Container nautobot-data-validation-engine-db-1  Waiting
 Container nautobot-data-validation-engine-db-1  Healthy
 Container nautobot-data-validation-engine-nautobot-1  Waiting
 Container nautobot-data-validation-engine-nautobot-1  Waiting
 Container nautobot-data-validation-engine-nautobot-1  Healthy
 Container nautobot-data-validation-engine-nautobot-1  Healthy
Running ruff...
Running docker compose command "ps --services --filter status=running"
Running docker compose command "exec nautobot ruff format --check ."
35 files already formatted
Running docker compose command "ps --services --filter status=running"
Running docker compose command "exec nautobot ruff check --output-format concise ."
All checks passed!
(nautobot-data-validation-engine-py3.10) steven:~/nautobot-app-data-validation-engine$
```

### Expected Behavior
All tests should be run. This issue appears to stem from the cookiecutter app temple v2.4.0 which introduces exit codes to the `ruff()` test.

The ruff function has the line `raise Exit(code=exit_code)`, which raises an Exit exception with the exit_code after `ruff` runs. This stops the `invoke tests` execution immediately, regardless of whether `ruff` succeeds or fails.

`invoke tests` calls `ruff(context)`, which then raises Exit upon completion, causing the script to exit immediately after ruff runs, without moving on to the subsequent steps.

### Steps to Reproduce

1. Run `invoke tests` for an app that has been rebaked using cookiecutter app template v2.4.0

**Comment by DistantVoyager** [comment]
This is also happening in the same way with the `pylint` test. 

When skipping the `ruff` test to allow `invoke tests` to continue, execution also stops even on a successful `pylint` run presumably due to the same exit exception code also in the `pylint()` method.

**Comment by gsnider2195** [comment]
Fixed in https://github.com/nautobot/cookiecutter-nautobot-app/pull/191
